#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("WhitePaperBible.Android.Resource", IsApplication=true)]

namespace WhitePaperBible.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			WhitePaperBible.Core.Resource.String.library_name = WhitePaperBible.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int custom_theme_color = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int HeaderBackground = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo_300 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int WPB_128 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int WPB_16 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int WPB_32 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int WPB_48 = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int detailsWebView = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int imageView1 = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int menu_search = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int progressBar1 = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int relativeLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int textView1 = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int titleTextView = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PaperDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PaperListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PapersList = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int ActionItems = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int PaperDetailsActionItems = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int GreenButton = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int GroupedListItem = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int GroupedListItemHeader = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int HeaderButton = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int IntroCard = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ListTitleFont = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
